name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          # Getting 500 so leaving commented out
          # cache: "yarn"

      - run: yarn install

      - run: yarn l test
